config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'tops#index'
  resources :tops do
  end

  get '/tweets', to: 'tweets#index'
  
  resources :tweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true
  validates :content,    length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def create
    #Tweet.create(content: params[:tweet][:content])
    #Tweet.create(params[:tweet])
    #Tweet.create(tweet_params)
    #redirect_to new_tweet_path
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to tweets_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
    
  end
  
  def show
    #@tweet = Tweet.find(params[:id])
  end
  
  def edit
    #@tweet = Tweet.find(params[:id])
  end
  
  def update
    #@tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice:"ブログを削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
  
  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
<header class="header">つぶやきアプリ</header>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">TwitterClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/tops/">TwitterClone</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/tweets/">投稿一覧</a></li>
            <li><a href="/tweets/new/">新規投稿</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
  <article>
    <div class="contents">
    </div>
    <div class="topic">
      <ul>
        <li>TwitterCloneのトップ画面です</li>
        <li>bootstrapで綺麗にするのはできませんした・・・</li>
      </ul>
    </div>
  </article>

app/views/tweets/_new_edit_form.html.erb
<%= form_with(model: @tweet, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tweet_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to '一覧画面にもどる', '/tweets' %>

app/views/tweets/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @tweet.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/tweets/edit.html.erb
<%= render 'form' %>

<h2>編集する</h2>

<%= render 'new_edit_form' %>

app/views/tweets/index.html.erb
<%= render 'form' %>

<div class="container">
  <% @tweets.each do |tweet| %>
    <div class="tweet-panel">
      <p><%= tweet.content %></p>
      <div class="tweet-links">
        <%= link_to '編集する', edit_tweet_path(tweet), class: 'btn btn-info' %>
        <%= link_to '削除する', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<%= render 'form' %>

<h2>作成する</h2>

<%= render 'new_edit_form' %>